### PR TITLE
Adding a TransferStatus class with the status constants.

### PR DESCRIPTION
**Pull request by iammichiel**
As the `Payin` and `Payout` have the `PayinStatus` and the `PayoutStatus` classes, the `Transfer` should have it's own `TransferStatus`. 

Obviously, this introduces no BC.

### CODE REVIEW

**Comment by paulhristea** [comment]
Hello @iammichiel, thanks for your contribution!

Your point is valid, yet I'd like to suggest deleting the three redundant `Status` classes, and keeping only one called `TransactionStatus`. I think this would be a more clear solution, seeing as the `Status` is only actually stored in a field within the `Transaction` class. Do you agree? If so, please update this pull request whenever you find the time (I tried to do it myself, but I do not have permissions to push to your fork!).

Tanks again!

**Comment by iammichiel** [comment]
That was indeed what I first had in mind, however deleting two classes (PayinStatus and PayoutStatus) will introduce a BC break. If we accept to make the BC break, there are many other things that might be updated as well.

**Comment by venyii** [comment]
We could simply mark them as deprecated as to not introduce any BC breaks

**Comment by mickaelpois** [comment]
Hi everybody, and thanks for brainstorming around our SDK !

I agree with you @venyii, the best solution would be a deprecation of these two classes, and a new `Status` class, but it could be a little bit messy, right?

**Pull request closed without merging**
