### PR TITLE
PSR-2

### PR DESCRIPTION
**Pull request by Falc**
This adds [PSR-2](http://www.php-fig.org/psr/psr-2/) compliance.

I have seen many trailing spaces polluting the code so I executed [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and the resulting code is slightly cleaner.

### CODE REVIEW

**Comment by hobailey** [comment]
Hi @Falc, thanks very much for this :-) We'll review this internally and keep in touch with you via this thread.

**Comment by Falc** [comment]
It should not break anything since PSR-2 is a set of guidelines added to PSR-1. The changes are related to braces, extra whitespaces at the end of the line or before/after parenthesis, etc.

**Comment by AntoineLemaire** [comment]
Any reason to not code with [PSR-1](http://www.php-fig.org/psr/psr-1/), especially camelCase ?

**Comment by Falc** [comment]
@AntoineLemaire PSR-2 does not prevent you from using camelCase. PSR-2 is primarily related to parentheses, braces and spaces. You don't have to choose between PSR-1 and PSR-2. A project can implement many PSRs.

PSR-2 allows to have a code styling standard. :)

**Comment by AntoineLemaire** [comment]
Yes I know, my question was not related with PSR-2, only PSR-1, I shouldn't have to ask it here

**Comment by iammichiel** [comment]
Great job, @Falc! 

@AntoineLemaire Applying PSR-1 would introduce massive BC breaks. Variables, functions, classes everything would be renamed and PHP is case-sensitive ;)

**Comment by shakaran** [comment]
This PR should be rebased again master, and I am giving my :+1: for this, since PSR-2 is almost a MUST in API-SDK payments for others companies.

**Comment by hobailey** [comment]
@Falc thanks very much for your original work on this, it's really helpful and hugely appreciated. We've (finally) got round to implementing it (note to self - do things quicker next time to avoid such horrific merge conflicts!)

**Comment by Falc** [comment]
Alternatively you could have executed php-cs-fixer on master branch, @hobailey. :sweat_smile:

There are some packages for php-cs-fixer integration with some popular IDEs:
* Atom: https://atom.io/packages/php-cs-fixer
* Sublime: https://github.com/benmatselby/sublime-phpcs

That allows to auto-execute a php-cs-fixer profile/configuration automatically when saving.

**Comment by hobailey** [comment]
@Falc, true - well I'll know for next time, thanks :-)

**Pull request closed without merging**
