### PR TITLE
Added `CardId` property to PayInExecutionDetailsDirect and used “int” as types for identifiers

### PR DESCRIPTION
**Pull request by garsaud**
To help with autocompletion and code scanning tools like Phpstan

### CODE REVIEW

**Comment by fredericdelordm** [comment]
Hello @garsaud,

Thank you for the PR. We are looking into it.

**Comment by garsaud** [comment]
@iulian03 Master branch is still causing CI failures, because 35e3910c22fc328aea86ae2852d1234937dfb7a3 is not merged yet

**Comment by iulian03** [comment]
@garsaud  we've just merged a PR that should fix all tests. Please update your PR again with the master branch, thanks! Sorry you had to do it twice :)

**Comment by garsaud** [comment]
@iulian03 “API Rate limit exceeded” 😭

**Comment by garsaud** [comment]
@iulian03 Is it all good now? 🙂

**Pull request merged**
