### PR TITLE
Master merge custom http client

### PR DESCRIPTION
**Pull request by gabriellupu**
Follow-up for #146. Fix conflicts and adapt the refactoring logic.

### CODE REVIEW

**Comment by gabriellupu** [comment]
@mickaelpois I have pushed the last updates including the Travis fix. This can be merged in. @tchiotludo thanks a lot for the updates!

**Comment by venyii** [comment]
Thank you for merging this! Do you plan to publish a release soon or will it take some time?

**Comment by mickaelpois** [comment]
Hi @venyii and thanks for your interest.
We will publish a release very soon (today or tomorrow), a lot of devs seems to be very interested about this merge !

**Comment by tchiotludo** [comment]
good news and thanks for the merge :tada:

**Pull request merged**
