### PR TITLE
Adding PSR Logger implementation

### PR DESCRIPTION
**Pull request by iammichiel**
Adds a PSR3 logger interface to the MangoPayApi. 

Solves #57

### CODE REVIEW

**Comment by iammichiel** [comment]
Could this be merged at some point?

**Comment by hobailey** [comment]
Hey @iammichiel, thanks again for your support with this.
Could you confirm what happens when you do not want use logging? There seems to be no way to disactivate it, and hence running this merge has is would result in breaking changes if I'm not mistaken:

    Fatal error: Class 'Psr\Log\NullLogger' not found in .../MangoPay/MangoPayApi.php on line 163

**Comment by iammichiel** [comment]
Hi @hobailey, 

The principle is quite simple. I have added a requirement in the composer.json. Meaning that when this is installed using composer another dependency is pulled as well `psr/log`. 

By default, psr/log included a NullLogger doing nothing with the debug message. If you want to have the message, you simply provide any other Logger implementation that is compatible with the PSR3 LoggerInterface. For example, you can use Monolog for that.

**Comment by hobailey** [comment]
OK, thanks for your quick reply. This is the approach I had assumed, but I do not see the `NullLogger` in your PR, and hence why when deploying your PR as is, I have an error. Do we not need to add something like https://github.com/php-fig/log/blob/master/Psr/Log/NullLogger.php?

**Comment by GabrielCC** [comment]
Hello guys,
Any update here? I've started to use mangopay in our project and we need the logging functionality.
Is there anything that I can do to help with this pull request?

Thanks,
Gabriel

**Comment by iammichiel** [comment]
@hobailey The `NullLogger` is provided by the `PSR\Log` dependency added in `composer.json`.

@GabrielCC Nope, this works perfectly.

**Comment by hobailey** [comment]
Of course, I didn't spot that - thanks for the clarification @iammichiel :-)

**Comment by hobailey** [comment]
@iammichiel coming back to my point regarding the breaking change etc, for those who do not use composer, this PR does infact present a breaking change :-( 
Do you have any suggestions to overcome this to adapt your PR for better compatability?

**Comment by iammichiel** [comment]
Yep, will make an update this afternoon.

**Comment by hobailey** [comment]
That would be great, thanks very much :-)

**Pull request merged**
